# Use an official Python runtime as a parent image
#FROM python:3.7-buster
FROM ubuntu:trusty
WORKDIR /tests

# Copy the current directory contents into the container at /app
COPY . /tests

# python and relevant tools
RUN apt-get update && apt-get install -y \ 
    curl \
    build-essential \
    python3 \
    python3-dev \
    libxml2-dev \
    libxslt-dev \
    libssl-dev \
    zlib1g-dev \
    libyaml-dev \
    libffi-dev \
    xvfb \
    firefox \
    python3-pip

# General dev tools
RUN apt-get install -y git

# Latest versions of python tools via pip
RUN pip install --upgrade pip \
                          virtualenv \
                          requests\
                          selenium \
                          behave
                        
                          
#ENV CHROMEDRIVER_VERSION 2.19
#ENV CHROMEDRIVER_DIR /chromedriver
#RUN mkdir $CHROMEDRIVER_DIR

# Download and install Chromedriver
#RUN wget -q --continue -P $CHROMEDRIVER_DIR "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
#RUN unzip $CHROMEDRIVER_DIR/chromedriver* -d $CHROMEDRIVER_DIR

# Put Chromedriver into the PATH
#ENV PATH $CHROMEDRIVER_DIR:$PATH
#RUN curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /chrome.deb
#RUN dpkg -i /chrome.deb || apt-get install -yf
#RUN rm /chrome.deb
#RUN curl https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip -o /usr/local/bin/chromedriver
#RUN chmod +x /usr/local/bin/chromedriver



CMD ["behave"]



# Docker image for behave and other Python-based SBE/BDD tools.
#
# URL: https://github.com/William-Yeh/docker-behave
#
# References: 
#   - https://eshlox.net/2016/11/22/dockerize-behave-selenium-tests/
#   - https://gist.github.com/ziadoz/3e8ab7e944d02fe872c3454d17af31a5
#
# For CJK font: https://github.com/elgalu/docker-selenium/pull/153
#
#
# Version     1.2.1
#


# pull base image
FROM python:3.6-slim-stretch

ENV CHROME_DRIVER_VERSION 76.0.3809.68
ENV CHROME_DRIVER_TARBALL http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip

RUN \
    echo "==> Install common stuff missing from the slim base image..."   && \
    apt-get update            && \
    apt-get install -y --no-install-recommends \
        gnupg   \
        dirmngr \
        wget    \
        ca-certificates               && \
        rm -rf /var/lib/apt/lists/*   && \
    \
    \
    \
    ##echo "==> Add Google repo for Chrome..."   && \
    ##wget -q -O- https://dl.google.com/linux/linux_signing_key.pub | apt-key add -  && \
    ##echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google.list  && \
    ##apt-get install -y gconf-service libasound2 libatk1.0-0 libcairo2 libcups2 libfontconfig1 libgdk-pixbuf2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libxss1 fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils && \
    ##wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    ##dpkg -i google-chrome-stable_current_amd64.deb --fix-missing; apt-get -fy install`\
    curl https://dl-ssl.google.com/linux/linux_signing_key.pub -o /tmp/google.pub \
    && cat /tmp/google.pub | apt-key add -; rm /tmp/google.pub \
    && echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google.list \
    && mkdir -p /usr/share/desktop-directories \
    && apt-get -y update && apt-get install -y google-chrome-stable \
   # Disable the SUID sandbox so that chrome can launch without being in a privileged container
    dpkg-divert --add --rename --divert /opt/google/chrome/google-chrome.real /opt/google/chrome/google-chrome \
    && echo "#!/bin/bash\nexec /opt/google/chrome/google-chrome.real --no-sandbox --disable-setuid-sandbox \"\$@\"" > /opt/google/chrome/google-chrome \
    && chmod 755 /opt/google/chrome/google-chrome \
    \
    \
    \
    echo "===> Test Line" && \
    echo "==> Install prerequisite stuff..."   && \
    apt-get update            && \
    apt-get install -y --no-install-recommends \
        python3-dev              \
        python3-pip              \
        xvfb                     \
        libfontconfig            \
        libfreetype6             \
        xfonts-scalable          \
        fonts-liberation         \
        fonts-noto-cjk           &&\
    \
    \
    echo "==> Install ChromeDriver..."   && \
    wget -qO- $CHROME_DRIVER_TARBALL | zcat > /usr/local/bin/chromedriver  && \
    chown root:root /usr/local/bin/chromedriver  && \
    chmod 0755 /usr/local/bin/chromedriver       && \
    \
    \
    \
    echo "==> Install useful Python stuff..."   && \
    pip3 install --no-cache-dir \
        requests                \
        unittest-xml-reporting  \
        nose                    \
        mockito                 \
        pyshould                \
                                && \
    \
    \
    echo "==> Install behave and related stuff..."   && \
    pip3 install --no-cache-dir \
        behave                  \
        selenium                \
        elementium              \
        capybara-py             \
        xvfbwrapper             && \
    \
    \
    echo "==> Clean up..."      && \
    rm -rf /var/lib/apt/lists/*


ENV PATH /usr/lib/chromium/:$PATH

#WORKDIR    /behave
#ENV        REQUIREMENTS_PATH  /behave/features/steps/requirements.txt

#COPY       wrapper.sh  /tmp
WORKDIR /tests

# Copy the current directory contents into the container at /tests
COPY . /tests
CMD ["behave"]
#ENTRYPOINT ["/tmp/wrapper.sh"]